name: 📚 Documentation Issue
description: Report an issue with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "needs-review"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the Heo framework documentation!

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: By submitting this documentation issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues to ensure this hasn't been reported before
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - Error or inaccuracy in existing documentation
        - Missing documentation for existing feature
        - Unclear or confusing documentation
        - Outdated documentation
        - Suggestion for new documentation
        - Typo or formatting issue
        - Translation issue
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Which documentation page or section is affected?
      placeholder: "e.g., docs/routing.md, README.md, Quick Start Guide, etc."
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the documentation currently say? (copy/paste the relevant section)
      render: markdown
      placeholder: Paste the current documentation content here...

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation or what's missing?
      placeholder: Describe the issue with the documentation...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      render: markdown
      placeholder: |
        Suggest the improved content or describe what should be added...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Why is this important? Who would benefit from this improvement?
      placeholder: "This would help developers who..."

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - Beginners to Heo framework
        - Experienced Heo users
        - Developers migrating from other frameworks
        - API reference users
        - All users
        - Other
    validations:
      required: true

  - type: checkboxes
    id: affected-sections
    attributes:
      label: Related Documentation Sections
      description: Which other documentation sections might be affected?
      options:
        - label: Installation guide
          required: false
        - label: Quick start tutorial
          required: false
        - label: Routing documentation
          required: false
        - label: Middleware documentation
          required: false
        - label: Error handling documentation
          required: false
        - label: Security documentation
          required: false
        - label: API reference
          required: false
        - label: Examples and code samples
          required: false

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: If applicable, provide code examples that should be included or corrected
      render: java
      placeholder: |
        // Example code that should be documented
        app.get("/example", (req, res, next) -> {
            // Implementation
        });

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to improving this documentation?
      options:
        - label: I would like to work on fixing this documentation issue
          required: false
        - label: I can provide additional examples for this documentation
          required: false
