name: ✨ Feature Request
description: Suggest an idea or enhancement for Heo framework
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand what you'd like to see added to Heo framework.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: By submitting this feature request, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have read the documentation and confirmed this feature doesn't already exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternatively, we could..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Core Framework
        - Routing
        - Middleware
        - Error Handling
        - Security
        - Performance
        - Documentation
        - Developer Experience
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Framework unusable without it
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: "In my application, I need to..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Implementation
      description: If you have ideas about how this could be implemented, please share them
      render: java
      placeholder: |
        // Example of how this feature might work
        app.newFeature((req, res) -> {
            // Implementation example
        });

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require any breaking changes to the existing API?
      placeholder: "This would/wouldn't require breaking changes because..."

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: What should we consider for compatibility?
      options:
        - label: This feature should be backward compatible
          required: false
        - label: This feature can introduce breaking changes if necessary
          required: false
        - label: This feature should work with all supported Java versions
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to implementing this feature?
      options:
        - label: I would like to work on implementing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false
        - label: I can help with testing this feature
          required: false
