name: 🚀 Performance Issue
description: Report a performance problem or suggest performance improvements
title: "[Performance]: "
labels: ["performance", "needs-investigation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve Heo framework performance! Performance issues help us make the framework better for everyone.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: By submitting this performance issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues to ensure this performance issue hasn't been reported before
          required: true
        - label: I have profiled my application to isolate the performance issue
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Performance Issue Type
      description: What type of performance issue are you experiencing?
      options:
        - Slow response times
        - High memory usage
        - High CPU usage
        - Memory leaks
        - Slow startup time
        - Throughput issues
        - Latency spikes
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem you're experiencing
      placeholder: "The application becomes slow when..."
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: Expected Performance
      description: What performance did you expect?
      placeholder: "I expected the response time to be under..."
    validations:
      required: true

  - type: textarea
    id: actual-performance
    attributes:
      label: Actual Performance
      description: What performance are you actually seeing?
      placeholder: "The actual response time is..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this performance issue?
      placeholder: |
        1. Create an application with...
        2. Send requests to...
        3. Monitor performance with...
        4. Observe slow performance
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Sample Code
      description: Provide code that demonstrates the performance issue
      render: java
      placeholder: |
        import heo.server.Heo;

        public class PerformanceExample {
            public static void main(String[] args) {
                Heo app = new Heo();
                // Code that shows the performance issue
                app.listen(8080);
            }
        }
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Performance Metrics
      description: Provide specific performance metrics (response times, memory usage, CPU usage, etc.)
      placeholder: |
        - Response time: 2000ms (expected: 100ms)
        - Memory usage: 1GB (expected: 200MB)
        - CPU usage: 80% (expected: 20%)
        - Requests per second: 10 (expected: 100)
    validations:
      required: true

  - type: textarea
    id: profiling
    attributes:
      label: Profiling Results
      description: Include results from profiling tools (JProfiler, VisualVM, etc.)
      render: text
      placeholder: |
        Paste profiling results here...
        Top methods by execution time:
        1. Method A - 45% of execution time
        2. Method B - 30% of execution time

  - type: dropdown
    id: load
    attributes:
      label: Load Conditions
      description: Under what load conditions does this performance issue occur?
      options:
        - Light load (1-10 concurrent users)
        - Medium load (10-100 concurrent users)
        - Heavy load (100-1000 concurrent users)
        - Extreme load (1000+ concurrent users)
        - Single user / minimal load
        - Stress testing conditions
    validations:
      required: true

  - type: input
    id: request-rate
    attributes:
      label: Request Rate
      description: What's the request rate when the issue occurs?
      placeholder: "e.g., 100 requests/second, 1000 requests/minute"

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide details about your testing environment
      placeholder: |
        - Hardware: CPU, RAM, disk type
        - Operating System: 
        - Java Version: 
        - JVM Arguments: 
        - Heo Version: 
        - Load testing tool:
    validations:
      required: true

  - type: textarea
    id: monitoring
    attributes:
      label: Monitoring Tools Used
      description: What tools did you use to measure performance?
      placeholder: |
        - JProfiler
        - VisualVM
        - Apache Bench (ab)
        - JMeter
        - Custom monitoring
        - Application Performance Monitoring (APM) tools

  - type: textarea
    id: comparison
    attributes:
      label: Performance Comparison
      description: How does this compare to other frameworks or previous versions?
      placeholder: "Compared to Express.js/Spring Boot/previous version..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help (graphs, logs, etc.)
      placeholder: Any additional performance data...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to fixing this performance issue?
      options:
        - label: I would like to work on optimizing this performance issue
          required: false
        - label: I can provide additional performance testing
          required: false
        - label: I can help with performance benchmarking
          required: false
