name: ❓ Question / Help
description: Ask a question about using Heo framework
title: "[Question]: "
labels: ["question", "help-wanted"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in Heo framework! We're here to help you succeed.

        **Before asking a question:**
        - Check the [documentation](https://github.com/102004tan/heo/tree/main/docs)
        - Search existing issues to see if your question has been answered
        - Look at the [examples](https://github.com/102004tan/heo/tree/main/examples) for common use cases

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: By submitting this question, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues to ensure this question hasn't been asked before
          required: true
        - label: I have read the relevant documentation
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question belong to?
      options:
        - Getting Started
        - Installation / Setup
        - Routing
        - Middleware
        - Request / Response Handling
        - Error Handling
        - Security / Authentication
        - Performance
        - Best Practices
        - Integration with other libraries
        - Deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "How do I..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide more context about what you're trying to achieve
      placeholder: "I'm trying to build an application that..."

  - type: textarea
    id: attempted
    attributes:
      label: What I've Tried
      description: What have you already tried? Include any code you've written
      render: java
      placeholder: |
        // Code I've tried so far
        Heo app = new Heo();
        // ...

  - type: textarea
    id: expected
    attributes:
      label: Expected Outcome
      description: What do you expect to happen or what result are you looking for?
      placeholder: "I expect to be able to..."

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: What version of Java are you using?
      placeholder: "e.g., Java 22, Java 17"

  - type: input
    id: heo-version
    attributes:
      label: Heo Version
      description: What version of Heo framework are you using?
      placeholder: "e.g., 1.0.0, main branch"

  - type: dropdown
    id: experience
    attributes:
      label: Experience Level
      description: How would you describe your experience with web frameworks?
      options:
        - Beginner - New to web development
        - Intermediate - Some experience with web frameworks
        - Advanced - Experienced with multiple frameworks
        - Expert - Very experienced with web development
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might help us answer your question
      placeholder: Any additional context...

  - type: checkboxes
    id: help-others
    attributes:
      label: Community
      description: After getting help, would you be interested in helping others?
      options:
        - label: I'd be interested in helping answer questions from other users
          required: false
        - label: I'd be interested in contributing to documentation based on this question
          required: false
