name: CI/CD - Automated Release

on:
  push:
    branches:
#      - main
      - test/cicd
#    paths-ignore:
#      - 'README.md'
#      - '.gitignore'
#      - 'CONTRIBUTING.md'
#      - 'docs/**'
#      - '.github/workflows/release.yml'

jobs:
  permissions:
    contents: read
    id-token: write
    repository-projects: write
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --file pom.xml


      - name: Get latest version
        id: get_version
        run: |
          git fetch --tags
          latest=$(git tag --list '1.0.*' --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest"
          if [ -z "$latest" ]; then
            echo "TAG=1.0.0" >> $GITHUB_ENV
          else
            patch=$(echo $latest | cut -d. -f3)
            next=$((patch + 1))
            echo "VERSION=1.0.$next" >> $GITHUB_ENV
          fi

      - name: Create new tag
        run: | 
           git tag "test/${VERSION}"
           git push origin "test/${VERSION}"