name: CI/CD - Automated Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'docs/**'
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 22 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

      - name: 🛠️ Build with Maven
        run: mvn clean package --file pom.xml
