name: CI/CD - Automated Release

on:
  push:
    tags:
        - 'test/*'
    branches:
#      - main
      - test/cicd
#    paths-ignore:
#      - 'README.md'
#      - '.gitignore'
#      - 'CONTRIBUTING.md'
#      - 'docs/**'
#      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
              Changes in this Release
              - First Change
              - Second Change
          draft: false
          prerelease: false